### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by shane-axiom** [ioos/i52n-sos#14]
Waiting on release of upstream 4.1.0 version (in progress now).

**Comment by abirger** [comment]
@shane-axiom , What is the status of the release 1.0.0? As of now, I see 0.8.1-SNAPSHOT installed at the RAs; would you consider that one to be a final Milestone 1.0 release?
The reason for my question is that IOOS Office would like to start baselining the SOS software in the field by pushing the RA upgrade to the official final Milestone 1.0 software versions. For ncSOS, it is v1.1, but what would that be for i52N?

**Comment by shane-axiom** [comment]
I still need to release 1.0.0. This repo is currently set to 1.0.0-SNAPSHOT, aka pre-1.0.0. I was trying to wait until ioos-sos-compliance-tests was complete so that full compliance to milestone 1.0 could be verified, but I still need to implement all of the GetObservation tests and I've helf off releasing 1.0.0 for way too long, so I'll just make minor formatting fixes to comply to the implemented GetCapabilities/DescribeSensor tests and release an incremental update to fix any GetObservation compliance issues later. 1.0.0 should be released next week, I'm out of the office until then.

**Comment by shane-axiom** [comment]
1.0.0 released, at long last.

**Comment by emiliom** [comment]
That's great, @shane-axiom! I see you're having fun on this long weekend ...

The [RELEASE-NOTES](https://github.com/ioos/i52n-sos/blob/master/RELEASE-NOTES) go from 0.8.1 to 1.0.0. Given that all/most of us have been on "1.0.0-SNAPSHOT" for so long, it seems like it could be useful to say something about significant changes from that version; I assume it's a small list, but still. Thanks for already laying down [specific instructions for upgrading 1.0.0-SNAPSHOT](http://ioos.github.io/i52n-sos/upgrade.html#1.0.0).

See you soon in Silver Spring, hopefully.

**Comment by shane-axiom** [comment]
Hi @emiliom, I thought everyone was still using 0.8.1-SNAPSHOT, but the upgrade instructions should be the same. If you're not using 0.8.1-SNAPSHOT and would like to verify, you can send me the build date of your SOS and I'll let you know. See you Wednesday.

**Comment by emiliom** [comment]
Yes, you're right about 0.8.1-SNAPSHOT! NANOOS (and I guess everyone else) is on that version. Sorry for the screw-up/confusion.
