### ISSUE TITLE
Updating phenomenon URI's in 52N SOS database

### ISSUE THREAD

**Issue by emiliom** [ioos/i52n-sos#20]
_(I posted this to the i52n list a few days ago, but I don't see it in the archives at http://librelist.com/browser/i52n/, so I assume it got lost in the librelist flakyness)_
Hi @shane-axiom  (et al),

I have some phenomenon URI's I need to update in a 52N SOS database. The ones entered originally (via sos-injector-db) were interim or incorrect (my fault, not sos-injector-db's).

What tables+fields have this information, so I can update them manually via SQL UPDATE queries? Is there a documentation page where I can find this myself, so you don't have to list them explicitly for me? Or is there a name or naming pattern used by these fields? eg, all such field names include the string "phenomenon".

Thanks, and Happy New Year.

**Comment by emiliom** [comment]
FYI, I looked through the database tables, and found what I was looking for. Looks like phenomenon uri's are stored in table *observableproperty*, field *identifier*. Fortunately uri's are not duplicated elsewhere.

**Comment by shane-axiom** [comment]
@emiliom Sorry I wasn't able to get to this in time.

You're mostly correct that the only database field explicitly containing phenomenon URIs is observableproperty.identifier. However, they also end up in the procedure SensorML descriptions in validproceduretime.descriptionxml, so you'll need to do the following as well (untested, as always back up database first):

```
UPDATE validproceduretime.descriptionxml
SET descriptionxml = replace(descriptionxml, 'http://mmisw.org/ont/old/parameter/some_old_param', 'http://mmisw.org/ont/new/parameter/some_new_param')
WHERE descriptionxml LIKE '%http://mmisw.org/ont/old/parameter/some_old_param%';
```

In some future revision of sos-injector I plan to implement UpdateSensor and this second step wouldn't be necessary, but I'm not there yet.

**Comment by shane-axiom** [comment]
Also moving mailing list to Google Groups:

https://groups.google.com/forum/#!forum/i52n-sos

**Comment by emiliom** [comment]
@shane-axiom, thanks for pointing out that other field to update. Yikes! I definitely wouldn't have caught it. Your SQL statement seems about right. I'll report back once I've made all updates, to both tables.

**Comment by emiliom** [comment]
I carried out the updates, and it seemed to work fine. Of course, you always discover an easier way when you're done ... So when I went to the 52N SOS Admin interface to update the GetCapabilities cache, I found that there's an Admin form that lets users manually change observable property uri's! I didn't try it b/c I was already done, but I'd look there first in the future, as it's much easier and less error prone than SQL statements. It's under *Admin > Settings > Observable Properties*.

**Comment by shane-axiom** [comment]
Hah, right, I meant to mention the Observable Properties rename admin page too. That will eliminate the need for the UPDATE query on `observableproperty.identifier`, but you'd still need to run the UPDATE on `validproceduretime.descriptionxml` which I mentioned above.

Also observable property renames done through the admin page will trigger a cache reload after each rename, so if your cache updates take a long time (large amount of procedures/observations in the db) you'd probably be better off running the `observableproperty` UPDATEs manually and then triggering a cache reload.

**Comment by shane-axiom** [comment]
Exploring including SensorML updates here: https://github.com/52North/SOS/issues/164

**Comment by emiliom** [comment]
Ah, thanks. Good to know those subtleties.
