### ISSUE TITLE
Add Docker/docker-compose support

### ISSUE THREAD

**Issue by shane-axiom** [ioos/i52n-sos#26]
Add a docker-compose file and sample Docker run commands for running i52n-sos in Docker. Also investigate uploading release images to https://hub.docker.com/r/ioos/.

**Comment by daf** [comment]
@lukecampbell is point man for ioos docker hub org.

**Comment by lukecampbell** [comment]
Let me know when you're ready and I can do an automatic build on dockerhub ioos. I can also do tagged releases.

**Comment by shane-axiom** [comment]
Completed in 1.1 release:
https://github.com/ioos/i52n-sos/releases/tag/1.1

**Comment by lukecampbell** [comment]
👍
