### ISSUE TITLE
New release planned (say, 1.0.1)?

### ISSUE THREAD

**Issue by emiliom** [ioos/i52n-sos#30]
@shane-axiom, are you planning to make a new release ("1.0.1"?) in the near future, to incorporate all the fixes and enhancements made so far this year? They add up to a bunch, and it'd be great to see them packaged as a release. Thanks.

**Comment by shane-axiom** [comment]
Yes, hoping to get most of the way there this weekend.

**Comment by emiliom** [comment]
Fantastic, thank you!!

**Comment by emiliom** [comment]
@shane-axiom, do you expect the installation/dependency requirements to change when you issue the next release, relative to what's listed at http://ioos.github.io/i52n-sos/install.html? I'm specially interested in anticipating changes in Java and Tomcat requirements, if any. Thanks.

**Comment by shane-axiom** [comment]
@emiliom Well, it will be Java 7/Tomcat 7. That's not what the project page says, but Java 7 was required for v1.0.0 also (v0.8.1 required Java 6).

As of 1.0.1 prebuilt Docker images are going to be available on IOOS' Docker Hub repository, so if you have Docker installed on a server that's an easy option.

**Comment by emiliom** [comment]
Thanks for the info.

**Comment by emiliom** [comment]
@shane-axiom, how is it going with plans for a 1.0.1 (or 1.0.+) release?

Thanks!

**Comment by shane-axiom** [comment]
@emiliom I was really trying to get something out by now, but there are a few more things I need to address before releasing. Unfortunately I'm also going to be out of the office until early May for leave and a meeting. I plan to sprint on a release as soon as I get back. Sorry for the delay.

**Comment by emiliom** [comment]
Thanks for the update. Good luck.

**Comment by emiliom** [comment]
@shane-axiom, you did say elsewhere that you're focusing on SOS this week, so here's a friendly reminder about this upcoming release :smiley_cat: ...

**Comment by shane-axiom** [comment]
Better late than never...

https://github.com/ioos/i52n-sos/releases/tag/1.1
