### ISSUE TITLE
Add WaterML observation encoding if possible

### ISSUE THREAD

**Issue by shane-axiom** [ioos/i52n-sos#31]
Ping Tad if it's added/released.

**Comment by emiliom** [comment]
Cool! I'm pasting this comment of mine from an email thread two months, in case it's useful:

> Ask whether they mean WaterML 2 or 1.x. They're different beasts. WaterML 2 is based on the SOS/SWE stack, but on the 2.0 generation; and I mean "SWE" in its umbrella meaning, not in the SWE Common encoding meaning. It doesn't use SWE Common. In fact, WaterML 2 is its own, official SOS 2 profile; it's currently being reworked and rebranded more generically as something like "TimeSeriesML".

> I don't know how widely implemented WaterML 2 is in the US, but I'm fairly sure that WaterML 1.x is more widely used. But WaterML 1.x will sooner or later be deprecated, I'm sure.

> I'm fairly certain that 52N SOS includes a WaterML 2 output encoding, at least if you request SOS 2.
