### ISSUE TITLE
Add migration docs and docker examples for i52n-sos 1.1

### ISSUE THREAD

**Issue by shane-axiom** [ioos/i52n-sos#32]
Update project site with documentation on how to upgrade to i52n-sos 1.1.

Also add some example Docker executions with the images on the IOOS Docker hub.

These should go on the project site:
http://ioos.github.io/i52n-sos/

**Comment by srstsavage** [comment]
Done. Docker documentation added to README so that it appears on the Docker Hub page.

https://hub.docker.com/r/ioos/i52n-sos/
